{
 "title": "Cluster View (Time Series)",
 "description": "Provides overview of cluster CPU, GPU, IB & NVLink metrics ",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job_id", "label": "Job ID", "query": { "query": "" } },
   {
    "name": "Operation",
    "query": "Average : 1, Minimum : 2,  Maximum : 3"
   },
   { "name": "Datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Node System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load",
   "type": "timeseries",
   "description": "Load average by node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(avg by(instance) (node_load1)) * ($Operation== bool 1) + (min by(instance) (node_load1)) * ($Operation== bool 2) + (max by(instance) (node_load1)) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - 1m"
    },
    {
     "expr": "(avg by(instance) (node_load5{instance=~\"$instance\"})) * ($Operation== bool 1) + (min by(instance) (node_load5{instance=~\"$instance\"})) * ($Operation== bool 2) + (max by(instance) (node_load5{instance=~\"$instance\"})) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - 5m"
    },
    {
     "expr": "(avg by(instance) (node_load15{instance=~\"$instance\"})) * ($Operation== bool 1) + (min by(instance) (node_load15{instance=~\"$instance\"})) * ($Operation== bool 2) + (max by(instance) (node_load15{instance=~\"$instance\"})) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - 15m"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "timeseries",
   "description": "Filesystem usage by node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by(instance) (100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}))) * ($Operation== bool 1) + (min by(instance) (100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}))) * ($Operation== bool 2) + (max by(instance) (100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "Selected Operation on CPU utilization across all nodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by(instance) (100 * (1 - avg by(instance, cpu) (rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])))))  *  ($Operation== bool 1)  + (min by(instance) (100 * (1 - avg by(instance, cpu) (rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])))))  *  ($Operation== bool 2)  + (max by(instance) (100 * (1 - avg by(instance, cpu) (rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])))))  *  ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Clock",
   "type": "timeseries",
   "description": "Selected Operation of VM CPU Clock",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "(avg by(instance) (node_cpu_scaling_frequency_hertz)/ 1000000)  *  ($Operation== bool 1)  + (min by(instance) (node_cpu_scaling_frequency_hertz)/ 1000000)  *  ($Operation== bool 2)  + (max by(instance) (node_cpu_scaling_frequency_hertz)/ 1000000)  *  ($Operation== bool 3)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "description": "Selected Operation on Memory utilization across all nodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by(instance) (100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)))) * ($Operation== bool 1) + (min by(instance) (100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)))) * ($Operation== bool 2) + (max by(instance) (100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ethernet Throughput (RX/TX)",
   "type": "timeseries",
   "description": "RX/TX rate of VM's Ethernet Interface by Node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum by(instance) (rate(node_network_receive_bytes_total{device='eth0'}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (rate(node_network_receive_bytes_total{device='eth0'}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (rate(node_network_receive_bytes_total{device='eth0'}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - receive"
    },
    {
     "expr": "(sum by(instance) (rate(node_network_transmit_bytes_total{device='eth0'}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (rate(node_network_transmit_bytes_total{device='eth0'}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (rate(node_network_transmit_bytes_total{device='eth0'}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - transmit"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "timeseries",
   "description": "Selected Operation of VM Available Memory",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "(avg by(instance) (node_memory_memavailable_bytes))  *  ($Operation== bool 1)  + (min by(instance) (node_memory_memavailable_bytes))  *  ($Operation== bool 2)  + (max by(instance) (node_memory_memavailable_bytes))  *  ($Operation== bool 3) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "description": "Disk Throughput(read & write) by node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(avg by(instance) (irate(node_disk_read_bytes_total[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (irate(node_disk_read_bytes_total[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (irate(node_disk_read_bytes_total[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - read"
    },
    {
     "expr": "(avg by(instance) (irate(node_disk_written_bytes_total[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (irate(node_disk_written_bytes_total[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (irate(node_disk_written_bytes_total[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - write"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization",
   "type": "timeseries",
   "description": "Disk I/O Utilization by node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(avg by(instance) (irate(node_disk_io_time_seconds_total[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (irate(node_disk_io_time_seconds_total[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (irate(node_disk_io_time_seconds_total[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NFS Throughput",
   "type": "timeseries",
   "description": "NFS Read/Write Throughput by node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_mountstats_nfs_total_read_bytes_total[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (irate(node_mountstats_nfs_total_read_bytes_total[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (irate(node_mountstats_nfs_total_read_bytes_total[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - read"
    },
    {
     "expr": "(sum by(instance) (irate(node_mountstats_nfs_total_write_bytes_total[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (irate(node_mountstats_nfs_total_write_bytes_total[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (irate(node_mountstats_nfs_total_write_bytes_total[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - write"
    }
   ]
  },
  {
   "title": "NFS I/O Operations",
   "type": "timeseries",
   "description": "NFS I/O Operations by node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "(avg by(instance) (irate(node_mountstats_nfs_operations_requests_total{operation=~\"^READ$\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (irate(node_mountstats_nfs_operations_requests_total{operation=~\"^READ$\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (irate(node_mountstats_nfs_operations_requests_total{operation=~\"^READ$\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - read"
    },
    {
     "expr": "(avg by(instance) (irate(node_mountstats_nfs_operations_requests_total{operation=~\"^WRITE$\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (irate(node_mountstats_nfs_operations_requests_total{operation=~\"^WRITE$\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (irate(node_mountstats_nfs_operations_requests_total{operation=~\"^WRITE$\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - write"
    }
   ]
  },
  { "title": "GPU Device Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "description": "Selected Operation on VM GPU device utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by(instance) (DCGM_FI_DEV_GPU_UTIL))  *  ($Operation== bool 1)  + (min by(instance) (DCGM_FI_DEV_GPU_UTIL))  *  ($Operation== bool 2)  + (max by(instance) (DCGM_FI_DEV_GPU_UTIL))  *  ($Operation== bool 3) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Copy Utilization",
   "type": "timeseries",
   "description": "Average of VM GPU device Memory utilization",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by(instance) (DCGM_FI_DEV_MEM_COPY_UTIL))  *  ($Operation== bool 1)  + (min by(instance) (DCGM_FI_DEV_MEM_COPY_UTIL))  *  ($Operation== bool 2)  + (max by(instance) (DCGM_FI_DEV_MEM_COPY_UTIL))  *  ($Operation== bool 3) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SM Clock ",
   "type": "timeseries",
   "description": "Selected Operation on VM GPU device SM Clock",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "(avg by(instance) (DCGM_FI_DEV_SM_CLOCK))  *  ($Operation== bool 1)  + (min by(instance) (DCGM_FI_DEV_SM_CLOCK))  *  ($Operation== bool 2)  + (max by(instance) (DCGM_FI_DEV_SM_CLOCK))  *  ($Operation== bool 3) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Clock",
   "type": "timeseries",
   "description": "Selected Operation of VM GPU device Memory Clock",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "(avg by(instance) (DCGM_FI_DEV_MEM_CLOCK))  *  ($Operation== bool 1)  + (min by(instance) (DCGM_FI_DEV_MEM_CLOCK))  *  ($Operation== bool 2)  + (max by(instance) (DCGM_FI_DEV_MEM_CLOCK))  *  ($Operation== bool 3) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "description": "Selected Operation of VM GPU device Temperature",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(avg by(instance) (DCGM_FI_DEV_GPU_TEMP))  *  ($Operation== bool 1)  + (min by(instance) (DCGM_FI_DEV_GPU_TEMP))  *  ($Operation== bool 2)  + (max by(instance) (DCGM_FI_DEV_GPU_TEMP))  *  ($Operation== bool 3) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "timeseries",
   "description": "Selected Operation of VM GPU device Memory Temperature",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(avg by(instance) (DCGM_FI_DEV_MEMORY_TEMP))  *  ($Operation== bool 1)  + (min by(instance) (DCGM_FI_DEV_MEMORY_TEMP))  *  ($Operation== bool 2)  + (max by(instance) (DCGM_FI_DEV_MEMORY_TEMP))  *  ($Operation== bool 3) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "description": "Selected Operation of VM GPU Power",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "(avg by(instance) (DCGM_FI_DEV_POWER_USAGE))  *  ($Operation== bool 1)  + (min by(instance) (DCGM_FI_DEV_POWER_USAGE))  *  ($Operation== bool 2)  + (max by(instance) (DCGM_FI_DEV_POWER_USAGE))  *  ($Operation== bool 3) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Energy Consumption",
   "type": "timeseries",
   "description": "Total energy consumption since boot (in mJ)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "(avg by(instance) (dcgm_fi_dev_total_energy_consumption)/ 10^3)  *  ($Operation== bool 1)  + (min by(hostname) (dcgm_fi_dev_total_energy_consumption)/ 10^3)  *  ($Operation== bool 2)  + (max by(instance) (dcgm_fi_dev_total_energy_consumption)/ 10^3)  *  ($Operation== bool 3) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last XID Code Present",
   "type": "table",
   "description": "Last XID Code Present(> 0 indicates XID error)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "DCGM_FI_DEV_XID_ERRORS", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Last Throttle Code",
   "type": "table",
   "description": "Last Throttle Code",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_CLOCKS_EVENT_REASONS",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SBE Persistent ECC Errors",
   "type": "timeseries",
   "description": "Total number of single-bit persistent ECC errors by node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg by(instance) (increase(dcgm_fi_dev_ecc_sbe_agg_total[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (increase(dcgm_fi_dev_ecc_sbe_agg_total[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (increase(dcgm_fi_dev_ecc_sbe_agg_total[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DBE Persistent ECC Errors",
   "type": "timeseries",
   "description": "Total number of double-bit persistent ECC errors by node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg by(instance) (increase(dcgm_fi_dev_ecc_dbe_agg_total[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (increase(dcgm_fi_dev_ecc_dbe_agg_total[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (increase(dcgm_fi_dev_ecc_dbe_agg_total[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "DBE Volatile ECC Errors",
   "type": "timeseries",
   "description": "Total number of double-bit volatile ECC errors by node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg by(instance) (increase(dcgm_fi_dev_ecc_dbe_vol_total[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (increase(dcgm_fi_dev_ecc_dbe_vol_total[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (increase(dcgm_fi_dev_ecc_dbe_vol_total[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SBE Volatile ECC Errors",
   "type": "timeseries",
   "description": "Total number of single-bit volatile ECC errors by node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg by(instance) (increase(dcgm_fi_dev_ecc_sbe_vol_total[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (increase(dcgm_fi_dev_ecc_sbe_vol_total[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (increase(dcgm_fi_dev_ecc_sbe_vol_total[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Thermal Violation Elapsed Time",
   "type": "timeseries",
   "description": "Thermal Violation Elapsed Time by node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "(avg by(instance) (increase(dcgm_fi_dev_thermal_violation[$__rate_interval]) / 1e9)) * ($Operation== bool 1) + (min by(instance) (increase(dcgm_fi_dev_thermal_violation[$__rate_interval]) / 1e9)) * ($Operation== bool 2) + (max by(instance) (increase(dcgm_fi_dev_thermal_violation[$__rate_interval]) / 1e9)) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power Violation Elapsed Time",
   "type": "timeseries",
   "description": "Power Violation Elapsed Time by node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "expr": "(avg by(instance) (increase(dcgm_fi_dev_power_violation[$__rate_interval]) / 1e9)) * ($Operation== bool 1) + (min by(instance) (increase(dcgm_fi_dev_power_violation[$__rate_interval]) / 1e9)) * ($Operation== bool 2) + (max by(instance) (increase(dcgm_fi_dev_power_violation[$__rate_interval]) / 1e9)) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Infiniband Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "IB Link Status",
   "type": "timeseries",
   "description": "IB link state by node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min by (instance) (node_infiniband_physical_state_id{device!=\"mlx5_an0\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last IB Link Flap",
   "type": "table",
   "description": "Last IB Link Flap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "clamp_max(increase(node_infiniband_link_downed_total[$__rate_interval]), 1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IB Throughput",
   "type": "timeseries",
   "description": "IB (RX+TX) throughput ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(avg by(instance) (rate(node_infiniband_port_data_received_bytes_total{device!=\"mlx5_an0\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (rate(node_infiniband_port_data_received_bytes_total{device!=\"mlx5_an0\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (rate(node_infiniband_port_data_received_bytes_total{device!=\"mlx5_an0\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - receive"
    },
    {
     "expr": "(avg by(instance) (rate(node_infiniband_port_data_transmitted_bytes_total{device!=\"mlx5_an0\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (rate(node_infiniband_port_data_transmitted_bytes_total{device!=\"mlx5_an0\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (rate(node_infiniband_port_data_transmitted_bytes_total{device!=\"mlx5_an0\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - transmit"
    }
   ]
  },
  {
   "title": "IB Port Receive Errors",
   "type": "timeseries",
   "description": "Port receive errors by node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg by(instance) (increase(node_infiniband_port_errors_received_total{device!=\"mlx5_an0\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (increase(node_infiniband_port_errors_received_total{device!=\"mlx5_an0\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (increase(node_infiniband_port_errors_received_total{device!=\"mlx5_an0\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IB Port Constraint Errors",
   "type": "timeseries",
   "description": "IB port constraint errors by node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg by(instance) (increase(node_infiniband_port_constraint_errors_received_total{device!=\"mlx5_an0\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (increase(node_infiniband_port_constraint_errors_received_total{device!=\"mlx5_an0\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (increase(node_infiniband_port_constraint_errors_received_total{device!=\"mlx5_an0\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IB Port Transmit Wait",
   "type": "timeseries",
   "description": "IB port transmit wait by node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg by(instance) (rate(node_infiniband_port_transmit_wait_total{device!=\"mlx5_an0\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (rate(node_infiniband_port_transmit_wait_total{device!=\"mlx5_an0\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (rate(node_infiniband_port_transmit_wait_total{device!=\"mlx5_an0\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IB Port Discards",
   "type": "timeseries",
   "description": "IB port discards by node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg by(instance) (rate(node_infiniband_port_discards_transmitted_total{device!=\"mlx5_an0\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (rate(node_infiniband_port_discards_transmitted_total{device!=\"mlx5_an0\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (rate(node_infiniband_port_discards_transmitted_total{device!=\"mlx5_an0\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - TX"
    },
    {
     "expr": "(avg by(instance) (rate(node_infiniband_port_discards_received_total{device!=\"mlx5_an0\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (rate(node_infiniband_port_discards_received_total{device!=\"mlx5_an0\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (rate(node_infiniband_port_discards_received_total{device!=\"mlx5_an0\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - RX"
    }
   ]
  },
  { "title": "NVLink Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "Last NVLink Recovery Failed Event",
   "type": "table",
   "description": "Last NVLink Recovery Failed Event",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "targets": [
    {
     "expr": "clamp_max(increase(dcgm_fi_dev_nvlink_count_link_recovery_failed_events[$__rate_interval]), 1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Link Integrity Errors",
   "type": "timeseries",
   "description": "Total number of times that the count of local errors exceeded the set threshold",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg by(instance) (increase(dcgm_fi_dev_nvlink_count_local_link_integrity_errors[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (increase(dcgm_fi_dev_nvlink_count_local_link_integrity_errors[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (increase(dcgm_fi_dev_nvlink_count_local_link_integrity_errors[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NVLink Throughput",
   "type": "timeseries",
   "description": "The rate of data received over NVLink, not including protocol headers, in bytes per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(avg by(instance) (rate(dcgm_fi_prof_nvlink_rx_bytes[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (rate(dcgm_fi_prof_nvlink_rx_bytes[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (rate(dcgm_fi_prof_nvlink_rx_bytes[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - receive "
    },
    {
     "expr": "(avg by(instance) (rate(dcgm_fi_prof_nvlink_tx_bytes[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (rate(dcgm_fi_prof_nvlink_tx_bytes[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (rate(dcgm_fi_prof_nvlink_tx_bytes[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - transmit"
    }
   ]
  },
  {
   "title": "Link RX Errors",
   "type": "timeseries",
   "description": "Total number of packets with errors Rx on a link",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg by(instance) (increase(dcgm_fi_dev_nvlink_count_rx_errors[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (increase(dcgm_fi_dev_nvlink_count_rx_errors[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (increase(dcgm_fi_dev_nvlink_count_rx_errors[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port TX Discards",
   "type": "timeseries",
   "description": "Total number of TX error packets that were discarded.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg by(instance) (increase(dcgm_fi_dev_nvlink_count_tx_discards[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (increase(dcgm_fi_dev_nvlink_count_tx_discards[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (increase(dcgm_fi_dev_nvlink_count_tx_discards[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}