{
 "title": "GPU Device View",
 "description": "dcgm_fi_dev_* Counters",
 "tags": [ "Moneo Refined" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "instance", "label": "Hostname", "query": { "query": "node_uname_info" } },
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values(dcgm_fi_dev_gpu_util{instance=\"$instance\"}, gpu)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "description": "GPU utilization (in %)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_gpu_util{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Memory Copy Utilization",
   "type": "timeseries",
   "description": "Memory utilization (in %)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_mem_copy_util{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  { "title": "Clock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "SM Clock",
   "type": "timeseries",
   "description": "SM clock frequency (in MHz)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_sm_clock{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Memory Clock",
   "type": "timeseries",
   "description": "Memory clock frequency (in MHz)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_mem_clock{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "description": "GPU temperature (in C)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_gpu_temp{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "timeseries",
   "description": "Memory temperature (in C)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_memory_temp{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "description": "Power usage (in W)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_power_usage{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Total Energy Consumption",
   "type": "timeseries",
   "description": "Total energy consumption since boot (in mJ)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_total_energy_consumption{instance=~\"$instance\", gpu=~\"$gpu\"} / 10^3",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  { "title": "XID", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "XID Codes",
   "type": "timeseries",
   "description": "XID Codes",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "dcgm_fi_dev_xid_errors{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  { "title": "ECC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "SBE Persistent ECC Errors",
   "type": "timeseries",
   "description": "Total number of single-bit persistent ECC errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_ecc_sbe_agg_total{instance=~\"$instance\", gpu=~\"$gpu\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "DBE Persistent ECC Errors",
   "type": "timeseries",
   "description": "Total number of double-bit persistent ECC errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_ecc_dbe_agg_total{instance=~\"$instance\", gpu=~\"$gpu\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "SBE Volatile ECC Errors",
   "type": "timeseries",
   "description": "Total number of single-bit volatile ECC errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_ecc_sbe_vol_total{instance=~\"$instance\", gpu=~\"$gpu\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "DBE Volatile ECC Errors",
   "type": "timeseries",
   "description": "Total number of double-bit volatile ECC errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_ecc_dbe_vol_total{instance=~\"$instance\", gpu=~\"$gpu\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  { "title": "GPU Throttling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "GPU Throttle Code",
   "type": "timeseries",
   "description": "Current throttle event reasons code ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_clocks_event_reasons{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Thermal Violation Elapsed Time",
   "type": "timeseries",
   "description": "Thermal Violation Elapsed Time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_thermal_violation{instance=~\"$instance\", gpu=~\"$gpu\"}[$__rate_interval]) / 1e9",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Power Violation Elapsed Time",
   "type": "timeseries",
   "description": "Power Violation Elapsed Time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_power_violation{instance=~\"$instance\", gpu=~\"$gpu\"}[$__rate_interval]) / 1e9",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  }
 ]
}